# Generated by Django 4.2.6 on 2023-11-17 04:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Aplication', '0003_delete_cliente_delete_proveedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=255, null=True)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('imagen', models.ImageField(default='default.jpg', upload_to='productos')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('producto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplication.producto')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
