# Generated by Django 4.2.6 on 2023-10-31 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='dir_mail',
            new_name='direccion_mail',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='tel',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='mail_prov',
            new_name='mail_proveedor',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombre_prov',
            new_name='nombre_proveedor',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='tel_prov',
            new_name='telefono_prov',
        ),
    ]
